---
title: "ZHUOHUI LIANG"
output:  pdf_document
fontsize : 10pt
geometry:
  margin=0.6in
header-includes:
    - \usepackage{setspace}\singlespacing
    - \usepackage{float}
    - \usepackage{blindtext}
    - \usepackage{hyperref}
---
<!-- **WORK PHONE** : +1 (646) 496-3283\newline -->
<!-- **MOBILE PHONE** : +861564129223\newline -->
<!-- **EMAIL 1** : [zl2974@cumc.columbia.edu](mailto:<zl2974@cumc.columbia.edu>) -->
<!-- \newline -->
<!-- **EMAIL 2** : [jeffreyliang1995@outlook.com](mailto:<jeffreyliang1995@outlook.com>) -->
<!-- \newline -->
<!-- **Linkedin** :  -->
<!-- [_Zhuohui Liang_](https://www.linkedin.com/in/zhuohui-liang-123108203/) -->

\begin{center}
\begin{tabular}{c|c|c}
WORK PHONE : +1 (646) 496-3283 & 
EMAIL 1 : \href{mailto:<zl2974@cumc.columbia.edu>}{zl2974@cumc.columbia.edu} &
EMAIL 2 : \href{mailto:<jeffreyliang1995@outlook.com>}{jeffreyliang1995@outlook.com}\\ 
\end{tabular}
\end{center}

## EDUCATION
- **INSTITUTE : COLUMBIA UNIVERSIY** \hfill New York City, U.S. \newline
  MAJOR : MASTER CANDIDATE IN BIOSTATISTICS(4.07/4.3) \hfill 09/2020-PRESENT
- **INSTITUTE : SHANDONG UNIVERSIY** \hfill Jinan, China\newline
  MAJOR : BACHELOR OF PUBLIC HEALTH(4.32/5) \hfill 09/2014-06/2019
  

## RESEARCH EXPERIENCE

- **Department of Biostatistics, Columbia University**
\hfill New York\newline
  _Research Assistant, Advisor: Prof. Shuang Wang_ \hfill 04/2021-PRESENT\newline
  **Methodology Developing on Multi-omic Association and Clustering **
  * Literature review on dimensional reduction, discrete time random walk and multi-view clustering and association singal boosting methods
  * Design simulation to test and compare existing multi-view clustering method, ie. Similarity Network Fusion(SNF), Multi-view Clustering Without Parameter(COMIC), Partition-level Multiview Subspace Clustering(PSMC), Diversity-Induce Multiview Clustering(DiMSC) and etc.; and association boosting method, ie. Disease-Specific Network Enhancement Prioritization(DISNEP), Gene-wanderer etc.
  * Experiment above-mentioned methods with alternative manifold learning for new data representation, smoothing learned similarity matrix with t-step self random walk, multi-view fusion or consensus, complementary regulation on clustering result to develop a method that can identify true number of clusters and clustering result under scenario which different view provide information only to find partial subtypes.
  
- **Department of Biostatistics, Columbia University**\hfill New York\newline
  _Research Assistant, Advisor: Prof. Ying Wei, Prof. Yifei Sun_ \hfill 09/2021-PRESENT\newline
  **Predicting Patient Aherence with Multivariate Random Forest**
  * Design and code weighted multivariate random forest algorithm independently to predict medication adherence in each interval for an incomplete medication adherence history  data;
  * Model missing pattern of the response variables under Missing At Random(MAR) assumption considering the missingness was mostly due to researchers' decisions. And boost compliance prediction model's performance with the inverse predicted missing observation probability(IPW) and see variables importance of baseline variables;
  * Ensemble all trees with Hidden Markov Chains model for a dynamic prediction model;
  * Design simulation study to test algorithm performance and analysis on the data, we found that using IPW to adjust for missing data improves the prediction performance of our multivariate random forest under MAR in simulation and our adherence history data;
  * Manuscript writing

- **Department of Social Health, Shandong University**
\hfill Jinan, China\newline
  _Research Assistant, Advisor: Prof. Jiajia Li_ \hfill 01/2019-06/2019\newline
  **Case Study: eHealth Resource Allocation Inequality in Shandong Province** 
  * collect data on the use of electronic health (eHealth) resources from an
online healthcare community involving more than 441,000 doctors and 31 provinces in China, by using Python packages, such as lxml and pandas.
  * Cleaned and visualize data with R-ggplot; utilized techniques such as visualizing the spatial distribution and density of highly-ranked hospitals and experienced professionals on map.
  * Performed statistical analysis on eHealth online-to-offline spillover effects using the Spatial Durbin Panel Model to reduce autocorrelation between regions; 
  * Identified the spillover effects of eHealth services on health care inequity between regions; provided suggestions and strategies to address healthcare disparities using widely accessible eHealth resources.
  * Drafted and submitted a report to the 2020 Health Technology Assessment International
Conference and 2019 Global Young Scholars Forum on Health Management

- **Department of Social Health, Shandong University**
\hfill Jinan, China\newline
  _Research Assistant, Advisor: Prof. Jiajia Li_ \hfill 10/2018-06/2019\newline
  **Project: Effect of Insurance Plans on Catastrophic Healthcare Expenditures**
  * Led a research group to conduct a study on the effects of different insurance types on catastrophic healthcare expenditures.
  * Conducted data cleansing using R package – tidyverse; processed information
from 44,417 observational sessions and identified 3,300 missing units of data and outliers.
  * Collected geographical locations based on provided address with Google Maps API and matched location with the insurance coverage provided by each plan as an instrumental variable for addressing the endogeneity introduced by insurance selection bias.
  * Performed two-stage least square regression analysis to build a model with instrumental variables using R package -AER; concluded that China's new health insurance program has decreased the odds of catastrophic health expenditures but has failed to control total health expenditures.
  * Provided quantitative evidence to forecast the financial expenditures of different healthcare insurance plans and to provide a reference for other researchers in the selection of instrumental variables.

<!-- - **Mapping Health: Tracking Population Health in Shandong Province, China**  -->
<!-- \hfill Jinan, China\newline -->
<!-- _Research Assistant; Advisor: Dr. Fuzhong Xue_ \hfill 06/2018-11/2018 -->
<!--   * Refined medical information from more than 161 handbooks on atrial fibrillation and -->
<!-- hypercholesterolemia; coded them into a graph database that covered more than 3,000 specific -->
<!-- nodes and relationships. -->
<!--   * Designed and constructed a Knowledge Graph in Neo4j, including processes for screening, -->
<!-- diagnosis, treatment, and education. -->

<!-- - **Urban-Rural Disparities in Catastrophic Health Expenditures in China** -->
<!-- \hfill Jinan,China\newline -->
<!-- _Lead Researcher; Advisor: Prof. Jiajia Li_ \hfill 03/2018-10/2018 -->
<!--   * Compared datasets with 44,417 observational sessions with individuals and 11,130 -->
<!-- observational sessions with households from the ten waves of the China Health and Nutrition -->
<!-- Survey (CHNS); examined registered residency status using R package-tidyverse. -->
<!--   * Calculated prevalence of catastrophic healthcare expenditures since 1989 in households with -->
<!-- chronic disease patients, and used this as a response variable; created an interaction of time with -->
<!-- rural-urban identities as an independent variable to use in future regression analysis. -->
<!--   * Performed logistics regression, concluding that healthcare disparities have diminished due to the -->
<!-- development of financial protection and rising standard of living, but that actual risk has not -->
<!-- been significantly reduced. -->
<!--   * Conducted a review of China's Health Reform progress and promoted critical illness insurance -->
<!-- among rural populations. -->
<!--   * Drafted a paper summarizing findings which was accepted by the 2019 International Health -->
<!-- Economics Association and 2018 Healthcare Management Forum, hosted by Chinese Preventive -->
<!-- Medicine Association. -->

## PUBLICATION

 Li,J., Li,S., Cao,W., Wang,Z., __Liang,Z.__, Fu, W., and Zhao, J. (2021). Appraisal of china’s response to the outbreak of covid-19 in comparison with sars. Frontiers in Public Health, 9:830
<!-- \bibliographystyle{apalike} -->
<!-- \bibliography{publication} -->

## WORK EXPERIENCE

- Mailman School of Public Health-Columbia University \hfill New York
\newline
 _Teaching Assistant_ __High-Dimensional EHR data Bootcamp__\hfill 09/2021-PRESENT
  * Course planning, material preparation and teaching lab session for `MIMIC Data Preparation and Sparse Coding` and  `Instrumental Variable Analysis Method` for __High-Dimensional EHR data Bootcamp__
  
- Mailman School of Public Health-Columbia University \hfill New York
\newline
 _Teaching Assistant_ __Data Science I P8105__\hfill 06/2021-09/2021
  * Course planning, holding office hour and grading for __Data Science I__

- National Health Development and Research Center of China Health Committee \hfill Beijing, China \newline
  _INTERN_ \hfill 06/2019-06/2020
  * Provide advice on sampling method, model selection, and result interpretation as well as data
visualization.
  * Estimate national health expenditure in 2019, and analyze the distribution of different
demographic characteristics, such as age and gender, to optimize healthcare resource allocation.
  * Build ICD-10 auto-coding and data format auto-standardizing algorithm with Python for annual health
accounting, improving working efficiency, data accuracy, and integrity.
  * Conduct a literature review on data mining methods for detecting healthcare fraud; provide
data support for a pilot feasibility project.
  * Participated in data visualization of healthcare metrics and healthcare access for _Development Report On Health Reform In China(2020)_(ISBN:9787520164412).
  * Assisted with study design and data processing in Python for two confidential projects

<!-- - Jinan Center for Disease Control and Prevention\hfill Jinan, China \newline -->
<!--   _INTERN_ \hfill 03/2019-05/2019 -->
<!--   * Completed a three-month rotation with various departments, including Chronic Diseases -->
<!-- Control, Occupation Disease Control, and Infectious Disease Control Centers. -->
<!--   * Monitored survival data in patients who presented with emergency cases and chronic diseases -->
<!-- in Jinan using R programming, following established procedures. -->

<!-- - Center of Health Data Science at Shandong University\hfill Jinan, China \newline -->
<!--   _INTERN_  \hfill 06/2018-11/2018 -->
<!--   * Conducted research on covariates adjustment and single nucleotide polymorphisms (SNPs) -->
<!-- identification in the Genome-wide Association Study (GWAS). -->
<!--   * Reviewed more than 200 published articles on cancer and cardiovascular diseases, categorized -->
<!-- them based on studied traits. -->
<!--   * Designed and constructed a database for all the articles, documenting specific SNPs, statistical -->
<!-- methods, adjusted covariates, interval validation results, and other parameters of each study -->

<!-- - Qianfoshan Hospital\hfill Jinan, China \newline -->
<!--   _INTERN_ \hfill 05/2017-10/2017  -->
<!--   * Monitored nutritional and health status of patients and collaborated with surgeons from the spine -->
<!-- surgery department, gynecology department, obstetrics department, and pediatrics department. -->

## SKILLS
- Computing: Python, R, Linux command line
